-- FIFA World Cup 2026 seed data.
--
-- This file intentionally seeds the official 48-team group draw plus the
-- official knockout bracket path that is knowable before group-stage results.
-- Knockout participants are represented as bracket-slot rows such as
-- "Group A winner" because the actual teams are not known until group play ends.
--
-- Primary sources:
-- https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/final-draw-results
-- https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums

PRAGMA foreign_keys = OFF;

DELETE FROM matches;
DELETE FROM teams;

PRAGMA foreign_keys = ON;

INSERT INTO teams (id, name, fifa_ranking, confederation, group_stage_record) VALUES
  ('mex', 'Mexico', NULL, 'CONCACAF', 'Group A'),
  ('rsa', 'South Africa', NULL, 'CAF', 'Group A'),
  ('kor', 'South Korea', NULL, 'AFC', 'Group A'),
  ('cze', 'Czechia', NULL, 'UEFA', 'Group A'),
  ('can', 'Canada', NULL, 'CONCACAF', 'Group B'),
  ('sui', 'Switzerland', NULL, 'UEFA', 'Group B'),
  ('qat', 'Qatar', NULL, 'AFC', 'Group B'),
  ('bih', 'Bosnia and Herzegovina', NULL, 'UEFA', 'Group B'),
  ('bra', 'Brazil', NULL, 'CONMEBOL', 'Group C'),
  ('mar', 'Morocco', NULL, 'CAF', 'Group C'),
  ('hai', 'Haiti', NULL, 'CONCACAF', 'Group C'),
  ('sco', 'Scotland', NULL, 'UEFA', 'Group C'),
  ('usa', 'United States', NULL, 'CONCACAF', 'Group D'),
  ('par', 'Paraguay', NULL, 'CONMEBOL', 'Group D'),
  ('aus', 'Australia', NULL, 'AFC', 'Group D'),
  ('tur', 'Turkiye', NULL, 'UEFA', 'Group D'),
  ('ger', 'Germany', NULL, 'UEFA', 'Group E'),
  ('cuw', 'Curacao', NULL, 'CONCACAF', 'Group E'),
  ('civ', 'Ivory Coast', NULL, 'CAF', 'Group E'),
  ('ecu', 'Ecuador', NULL, 'CONMEBOL', 'Group E'),
  ('ned', 'Netherlands', NULL, 'UEFA', 'Group F'),
  ('jpn', 'Japan', NULL, 'AFC', 'Group F'),
  ('tun', 'Tunisia', NULL, 'CAF', 'Group F'),
  ('swe', 'Sweden', NULL, 'UEFA', 'Group F'),
  ('bel', 'Belgium', NULL, 'UEFA', 'Group G'),
  ('egy', 'Egypt', NULL, 'CAF', 'Group G'),
  ('irn', 'Iran', NULL, 'AFC', 'Group G'),
  ('nzl', 'New Zealand', NULL, 'OFC', 'Group G'),
  ('esp', 'Spain', NULL, 'UEFA', 'Group H'),
  ('cpv', 'Cape Verde', NULL, 'CAF', 'Group H'),
  ('ksa', 'Saudi Arabia', NULL, 'AFC', 'Group H'),
  ('uru', 'Uruguay', NULL, 'CONMEBOL', 'Group H'),
  ('fra', 'France', NULL, 'UEFA', 'Group I'),
  ('sen', 'Senegal', NULL, 'CAF', 'Group I'),
  ('nor', 'Norway', NULL, 'UEFA', 'Group I'),
  ('irq', 'Iraq', NULL, 'AFC', 'Group I'),
  ('arg', 'Argentina', NULL, 'CONMEBOL', 'Group J'),
  ('alg', 'Algeria', NULL, 'CAF', 'Group J'),
  ('aut', 'Austria', NULL, 'UEFA', 'Group J'),
  ('jor', 'Jordan', NULL, 'AFC', 'Group J'),
  ('por', 'Portugal', NULL, 'UEFA', 'Group K'),
  ('uzb', 'Uzbekistan', NULL, 'AFC', 'Group K'),
  ('col', 'Colombia', NULL, 'CONMEBOL', 'Group K'),
  ('cod', 'DR Congo', NULL, 'CAF', 'Group K'),
  ('eng', 'England', NULL, 'UEFA', 'Group L'),
  ('cro', 'Croatia', NULL, 'UEFA', 'Group L'),
  ('gha', 'Ghana', NULL, 'CAF', 'Group L'),
  ('pan', 'Panama', NULL, 'CONCACAF', 'Group L'),

  ('ga_winner', 'Group A winner (Mexico, South Africa, South Korea, Czechia)', NULL, 'BRACKET_SLOT', NULL),
  ('gb_winner', 'Group B winner (Canada, Switzerland, Qatar, Bosnia and Herzegovina)', NULL, 'BRACKET_SLOT', NULL),
  ('gc_winner', 'Group C winner (Brazil, Morocco, Haiti, Scotland)', NULL, 'BRACKET_SLOT', NULL),
  ('gd_winner', 'Group D winner (United States, Paraguay, Australia, Turkiye)', NULL, 'BRACKET_SLOT', NULL),
  ('ge_winner', 'Group E winner (Germany, Curacao, Ivory Coast, Ecuador)', NULL, 'BRACKET_SLOT', NULL),
  ('gf_winner', 'Group F winner (Netherlands, Japan, Tunisia, Sweden)', NULL, 'BRACKET_SLOT', NULL),
  ('gg_winner', 'Group G winner (Belgium, Egypt, Iran, New Zealand)', NULL, 'BRACKET_SLOT', NULL),
  ('gh_winner', 'Group H winner (Spain, Cape Verde, Saudi Arabia, Uruguay)', NULL, 'BRACKET_SLOT', NULL),
  ('gi_winner', 'Group I winner (France, Senegal, Norway, Iraq)', NULL, 'BRACKET_SLOT', NULL),
  ('gj_winner', 'Group J winner (Argentina, Algeria, Austria, Jordan)', NULL, 'BRACKET_SLOT', NULL),
  ('gk_winner', 'Group K winner (Portugal, Uzbekistan, Colombia, DR Congo)', NULL, 'BRACKET_SLOT', NULL),
  ('gl_winner', 'Group L winner (England, Croatia, Ghana, Panama)', NULL, 'BRACKET_SLOT', NULL),
  ('ga_runner_up', 'Group A runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gb_runner_up', 'Group B runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gc_runner_up', 'Group C runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gd_runner_up', 'Group D runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('ge_runner_up', 'Group E runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gf_runner_up', 'Group F runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gg_runner_up', 'Group G runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gh_runner_up', 'Group H runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gi_runner_up', 'Group I runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gj_runner_up', 'Group J runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gk_runner_up', 'Group K runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('gl_runner_up', 'Group L runner-up', NULL, 'BRACKET_SLOT', NULL),
  ('third_a_b_c_d_f', 'Third-place qualifier from Group A/B/C/D/F', NULL, 'BRACKET_SLOT', NULL),
  ('third_c_d_f_g_h', 'Third-place qualifier from Group C/D/F/G/H', NULL, 'BRACKET_SLOT', NULL),
  ('third_c_e_f_h_i', 'Third-place qualifier from Group C/E/F/H/I', NULL, 'BRACKET_SLOT', NULL),
  ('third_e_h_i_j_k', 'Third-place qualifier from Group E/H/I/J/K', NULL, 'BRACKET_SLOT', NULL),
  ('third_b_e_f_i_j', 'Third-place qualifier from Group B/E/F/I/J', NULL, 'BRACKET_SLOT', NULL),
  ('third_a_e_h_i_j', 'Third-place qualifier from Group A/E/H/I/J', NULL, 'BRACKET_SLOT', NULL),
  ('third_e_f_g_i_j', 'Third-place qualifier from Group E/F/G/I/J', NULL, 'BRACKET_SLOT', NULL),
  ('third_d_e_i_j_l', 'Third-place qualifier from Group D/E/I/J/L', NULL, 'BRACKET_SLOT', NULL),
  ('wm73', 'Winner match 73', NULL, 'BRACKET_SLOT', NULL),
  ('wm74', 'Winner match 74', NULL, 'BRACKET_SLOT', NULL),
  ('wm75', 'Winner match 75', NULL, 'BRACKET_SLOT', NULL),
  ('wm76', 'Winner match 76', NULL, 'BRACKET_SLOT', NULL),
  ('wm77', 'Winner match 77', NULL, 'BRACKET_SLOT', NULL),
  ('wm78', 'Winner match 78', NULL, 'BRACKET_SLOT', NULL),
  ('wm79', 'Winner match 79', NULL, 'BRACKET_SLOT', NULL),
  ('wm80', 'Winner match 80', NULL, 'BRACKET_SLOT', NULL),
  ('wm81', 'Winner match 81', NULL, 'BRACKET_SLOT', NULL),
  ('wm82', 'Winner match 82', NULL, 'BRACKET_SLOT', NULL),
  ('wm83', 'Winner match 83', NULL, 'BRACKET_SLOT', NULL),
  ('wm84', 'Winner match 84', NULL, 'BRACKET_SLOT', NULL),
  ('wm85', 'Winner match 85', NULL, 'BRACKET_SLOT', NULL),
  ('wm86', 'Winner match 86', NULL, 'BRACKET_SLOT', NULL),
  ('wm87', 'Winner match 87', NULL, 'BRACKET_SLOT', NULL),
  ('wm88', 'Winner match 88', NULL, 'BRACKET_SLOT', NULL),
  ('wm89', 'Winner match 89', NULL, 'BRACKET_SLOT', NULL),
  ('wm90', 'Winner match 90', NULL, 'BRACKET_SLOT', NULL),
  ('wm91', 'Winner match 91', NULL, 'BRACKET_SLOT', NULL),
  ('wm92', 'Winner match 92', NULL, 'BRACKET_SLOT', NULL),
  ('wm93', 'Winner match 93', NULL, 'BRACKET_SLOT', NULL),
  ('wm94', 'Winner match 94', NULL, 'BRACKET_SLOT', NULL),
  ('wm95', 'Winner match 95', NULL, 'BRACKET_SLOT', NULL),
  ('wm96', 'Winner match 96', NULL, 'BRACKET_SLOT', NULL),
  ('wm97', 'Winner match 97', NULL, 'BRACKET_SLOT', NULL),
  ('wm98', 'Winner match 98', NULL, 'BRACKET_SLOT', NULL),
  ('wm99', 'Winner match 99', NULL, 'BRACKET_SLOT', NULL),
  ('wm100', 'Winner match 100', NULL, 'BRACKET_SLOT', NULL),
  ('wm101', 'Winner match 101', NULL, 'BRACKET_SLOT', NULL),
  ('wm102', 'Winner match 102', NULL, 'BRACKET_SLOT', NULL);

INSERT INTO matches (id, round, slot, team_a_id, team_b_id, scheduled_time, status) VALUES
  ('match_73', 'R32', 'R32-73', 'ga_runner_up', 'gb_runner_up', 1782604800, 'pending'),
  ('match_74', 'R32', 'R32-74', 'ge_winner', 'third_a_b_c_d_f', 1782691200, 'pending'),
  ('match_75', 'R32', 'R32-75', 'gf_winner', 'gc_runner_up', 1782691200, 'pending'),
  ('match_76', 'R32', 'R32-76', 'gc_winner', 'gf_runner_up', 1782691200, 'pending'),
  ('match_77', 'R32', 'R32-77', 'gi_winner', 'third_c_d_f_g_h', 1782777600, 'pending'),
  ('match_78', 'R32', 'R32-78', 'ge_runner_up', 'gi_runner_up', 1782777600, 'pending'),
  ('match_79', 'R32', 'R32-79', 'ga_winner', 'third_c_e_f_h_i', 1782777600, 'pending'),
  ('match_80', 'R32', 'R32-80', 'gl_winner', 'third_e_h_i_j_k', 1782864000, 'pending'),
  ('match_81', 'R32', 'R32-81', 'gd_winner', 'third_b_e_f_i_j', 1782864000, 'pending'),
  ('match_82', 'R32', 'R32-82', 'gg_winner', 'third_a_e_h_i_j', 1782864000, 'pending'),
  ('match_83', 'R32', 'R32-83', 'gk_runner_up', 'gl_runner_up', 1782950400, 'pending'),
  ('match_84', 'R32', 'R32-84', 'gh_winner', 'gj_runner_up', 1782950400, 'pending'),
  ('match_85', 'R32', 'R32-85', 'gb_winner', 'third_e_f_g_i_j', 1782950400, 'pending'),
  ('match_86', 'R32', 'R32-86', 'gj_winner', 'gh_runner_up', 1783036800, 'pending'),
  ('match_87', 'R32', 'R32-87', 'gk_winner', 'third_d_e_i_j_l', 1783036800, 'pending'),
  ('match_88', 'R32', 'R32-88', 'gd_runner_up', 'gg_runner_up', 1783036800, 'pending'),
  ('match_89', 'R16', 'R16-89', 'wm74', 'wm77', 1783123200, 'pending'),
  ('match_90', 'R16', 'R16-90', 'wm73', 'wm75', 1783123200, 'pending'),
  ('match_91', 'R16', 'R16-91', 'wm76', 'wm78', 1783209600, 'pending'),
  ('match_92', 'R16', 'R16-92', 'wm79', 'wm80', 1783209600, 'pending'),
  ('match_93', 'R16', 'R16-93', 'wm83', 'wm84', 1783296000, 'pending'),
  ('match_94', 'R16', 'R16-94', 'wm81', 'wm82', 1783296000, 'pending'),
  ('match_95', 'R16', 'R16-95', 'wm86', 'wm88', 1783382400, 'pending'),
  ('match_96', 'R16', 'R16-96', 'wm85', 'wm87', 1783382400, 'pending'),
  ('match_97', 'QF', 'QF-97', 'wm89', 'wm90', 1783555200, 'pending'),
  ('match_98', 'QF', 'QF-98', 'wm93', 'wm94', 1783641600, 'pending'),
  ('match_99', 'QF', 'QF-99', 'wm91', 'wm92', 1783728000, 'pending'),
  ('match_100', 'QF', 'QF-100', 'wm95', 'wm96', 1783728000, 'pending'),
  ('match_101', 'SF', 'SF-101', 'wm97', 'wm98', 1783987200, 'pending'),
  ('match_102', 'SF', 'SF-102', 'wm99', 'wm100', 1784073600, 'pending'),
  ('match_104', 'F', 'F-104', 'wm101', 'wm102', 1784419200, 'pending');
